-- Custom Chat Filter - Chat Hub
-- Activities.lua
CustomChatFilter = CustomChatFilter or {}
local CCF = CustomChatFilter

CCF.ActivityDB = {
    instances = {
        { id="rfc", name="Ragefire Chasm", short="RFC", expansion="Classic", kind="Dungeon", aliases={ "rfc", "ragefire", "ragefire chasm" } },
        { id="wc", name="Wailing Caverns", short="WC", expansion="Classic", kind="Dungeon", aliases={ "wc", "wailing caverns" } },
        { id="deadmines", name="The Deadmines", short="VC", expansion="Classic", kind="Dungeon", aliases={ "vc", "deadmines", "the deadmines", "dead mines" } },
        { id="sfk", name="Shadowfang Keep", short="SFK", expansion="Classic", kind="Dungeon", aliases={ "sfk", "shadowfang", "shadowfang keep" } },
        { id="bfd", name="Blackfathom Deeps", short="BFD", expansion="Classic", kind="Dungeon", aliases={ "bfd", "blackfathom", "blackfathom deeps" } },
        { id="stocks", name="The Stockade", short="Stocks", expansion="Classic", kind="Dungeon", aliases={ "stocks", "stockades", "the stockade" } },
        { id="gnomer", name="Gnomeregan", short="Gnomer", expansion="Classic", kind="Dungeon", aliases={ "gnomer", "gnomeregan" } },
        { id="rfk", name="Razorfen Kraul", short="RFK", expansion="Classic", kind="Dungeon", aliases={ "rfk", "razorfen kraul" } },
        { id="sm", name="Scarlet Monastery", short="SM", expansion="Classic", kind="Dungeon", aliases={ "sm", "scarlet monastery" } },
        { id="sm_gy", name="Scarlet Monastery: Graveyard", short="SM GY", expansion="Classic", kind="Dungeon", aliases={ "sm gy", "smgy", "scarlet graveyard" } },
        { id="sm_lib", name="Scarlet Monastery: Library", short="SM Lib", expansion="Classic", kind="Dungeon", aliases={ "sm lib", "smlib", "scarlet library" } },
        { id="sm_arm", name="Scarlet Monastery: Armory", short="SM Arm", expansion="Classic", kind="Dungeon", aliases={ "sm arm", "smarm", "scarlet armory" } },
        { id="sm_cath", name="Scarlet Monastery: Cathedral", short="SM Cath", expansion="Classic", kind="Dungeon", aliases={ "sm cath", "smcath", "scarlet cathedral" } },
        { id="rfd", name="Razorfen Downs", short="RFD", expansion="Classic", kind="Dungeon", aliases={ "rfd", "razorfen downs" } },
        { id="ulda", name="Uldaman", short="Ulda", expansion="Classic", kind="Dungeon", aliases={ "ulda", "uldaman" } },
        { id="zf", name="Zul'Farrak", short="ZF", expansion="Classic", kind="Dungeon", aliases={ "zf", "zul farrak", "zulfarrak" } },
        { id="mara", name="Maraudon", short="Mara", expansion="Classic", kind="Dungeon", aliases={ "mara", "maraudon", "princess run" } },
        { id="st", name="The Temple of Atal'Hakkar", short="ST", expansion="Classic", kind="Dungeon", aliases={ "st", "sunken temple", "temple of atal hakkar" } },
        { id="brd", name="Blackrock Depths", short="BRD", expansion="Classic", kind="Dungeon", aliases={ "brd", "blackrock depths" } },
        { id="lbrs", name="Lower Blackrock Spire", short="LBRS", expansion="Classic", kind="Dungeon", aliases={ "lbrs", "lower blackrock spire" } },
        { id="ubrs", name="Upper Blackrock Spire", short="UBRS", expansion="Classic", kind="Dungeon", aliases={ "ubrs", "upper blackrock spire" } },
        { id="dme", name="Dire Maul East", short="DM East", expansion="Classic", kind="Dungeon", aliases={ "dme", "dm east", "dire maul east" } },
        { id="dmw", name="Dire Maul West", short="DM West", expansion="Classic", kind="Dungeon", aliases={ "dmw", "dm west", "dire maul west" } },
        { id="dmn", name="Dire Maul North", short="DM North", expansion="Classic", kind="Dungeon", aliases={ "dmn", "dm north", "dire maul north", "tribute run", "dm tribute" } },
        { id="diremaul", name="Dire Maul", short="Dire Maul", expansion="Classic", kind="Dungeon", aliases={ "dire maul" } },
        { id="strat", name="Stratholme", short="Strat", expansion="Classic", kind="Dungeon", aliases={ "strat", "stratholme", "strat live", "strat ud", "strat undead" } },
        { id="scholo", name="Scholomance", short="Scholo", expansion="Classic", kind="Dungeon", aliases={ "scholo", "scholomance" } },
        { id="mc", name="Molten Core", short="MC", expansion="Classic", kind="Raid", aliases={ "mc", "molten core" } },
        { id="ony", name="Onyxia's Lair", short="Ony", expansion="Classic", kind="Raid", aliases={ "ony", "onyxia", "onyxia's lair", "onyxia lair" } },
        { id="bwl", name="Blackwing Lair", short="BWL", expansion="Classic", kind="Raid", aliases={ "bwl", "blackwing lair" } },
        { id="zg", name="Zul'Gurub", short="ZG", expansion="Classic", kind="Raid", aliases={ "zg", "zul gurub", "zulgurub" } },
        { id="aq20", name="Ruins of Ahn'Qiraj", short="AQ20", expansion="Classic", kind="Raid", aliases={ "aq20", "aq 20", "ruins of ahn qiraj" } },
        { id="aq40", name="Temple of Ahn'Qiraj", short="AQ40", expansion="Classic", kind="Raid", aliases={ "aq40", "aq 40", "temple of ahn qiraj" } },
        { id="ramps", name="Hellfire Ramparts", short="Ramps", expansion="TBC", kind="Dungeon", aliases={ "ramps", "ramparts", "hellfire ramparts" } },
        { id="bf", name="The Blood Furnace", short="BF", expansion="TBC", kind="Dungeon", aliases={ "bf", "blood furnace" } },
        { id="shh", name="The Shattered Halls", short="SHH", expansion="TBC", kind="Dungeon", aliases={ "shh", "shattered halls", "the shattered halls" } },
        { id="sp", name="The Slave Pens", short="SP", expansion="TBC", kind="Dungeon", aliases={ "sp", "slave pens" } },
        { id="ub", name="The Underbog", short="UB", expansion="TBC", kind="Dungeon", aliases={ "ub", "underbog" } },
        { id="sv", name="The Steamvault", short="SV", expansion="TBC", kind="Dungeon", aliases={ "sv", "steamvault", "steam vault" } },
        { id="mt", name="Mana-Tombs", short="MT", expansion="TBC", kind="Dungeon", aliases={ "mt", "mana tombs", "mana-tombs" } },
        { id="ac", name="Auchenai Crypts", short="AC", expansion="TBC", kind="Dungeon", aliases={ "ac", "auchenai crypts" } },
        { id="sethekk", name="Sethekk Halls", short="Sethekk", expansion="TBC", kind="Dungeon", aliases={ "sethekk", "sethekk halls", "shalls" } },
        { id="sl", name="Shadow Labyrinth", short="SL", expansion="TBC", kind="Dungeon", aliases={ "sl", "shadow lab", "shadow labs", "shadow labyrinth", "slabs" } },
        { id="ohb", name="Old Hillsbrad Foothills", short="OHB", expansion="TBC", kind="Dungeon", aliases={ "ohb", "old hillsbrad", "durnholde", "escape from durnholde" } },
        { id="bm", name="The Black Morass", short="BM", expansion="TBC", kind="Dungeon", aliases={ "bm", "black morass", "the black morass" } },
        { id="mech", name="The Mechanar", short="Mech", expansion="TBC", kind="Dungeon", aliases={ "mech", "mechanar", "the mechanar" } },
        { id="bot", name="The Botanica", short="Bot", expansion="TBC", kind="Dungeon", aliases={ "bot", "botanica", "the botanica" } },
        { id="arc", name="The Arcatraz", short="Arc", expansion="TBC", kind="Dungeon", aliases={ "arc", "arcatraz", "the arcatraz" } },
        { id="mgt", name="Magisters' Terrace", short="MgT", expansion="TBC", kind="Dungeon", aliases={ "mgt", "magisters terrace", "magister's terrace", "magisters' terrace" } },
        { id="kara", name="Karazhan", short="Kara", expansion="TBC", kind="Raid", aliases={ "kara", "karazhan" } },
        { id="gruul", name="Gruul's Lair", short="Gruul", expansion="TBC", kind="Raid", aliases={ "gruul", "gruuls lair", "gruul's lair" } },
        { id="mag", name="Magtheridon's Lair", short="Mag", expansion="TBC", kind="Raid", aliases={ "mag", "magtheridon", "magtheridon's lair", "magtheridons lair" } },
        { id="ssc", name="Serpentshrine Cavern", short="SSC", expansion="TBC", kind="Raid", aliases={ "ssc", "serpentshrine", "serpentshrine cavern" } },
        { id="tk", name="The Eye", short="TK", expansion="TBC", kind="Raid", aliases={ "tk", "the eye", "tempest keep raid", "tempest keep" } },
        { id="hyjal", name="The Battle for Mount Hyjal", short="Hyjal", expansion="TBC", kind="Raid", aliases={ "hyjal", "mh", "mount hyjal", "battle for mount hyjal" } },
        { id="bt", name="Black Temple", short="BT", expansion="TBC", kind="Raid", aliases={ "bt", "black temple" } },
        { id="za", name="Zul'Aman", short="ZA", expansion="TBC", kind="Raid", aliases={ "za", "zul aman", "zulaman" } },
        { id="swp", name="Sunwell Plateau", short="SWP", expansion="TBC", kind="Raid", aliases={ "swp", "sunwell", "sunwell plateau" } },
        { id="uk", name="Utgarde Keep", short="UK", expansion="Wrath", kind="Dungeon", aliases={ "uk", "utgarde keep" } },
        { id="nexus", name="The Nexus", short="Nexus", expansion="Wrath", kind="Dungeon", aliases={ "nexus", "the nexus" } },
        { id="an", name="Azjol-Nerub", short="AN", expansion="Wrath", kind="Dungeon", aliases={ "an", "azjol nerub", "azjol-nerub" } },
        { id="ok", name="Ahn'kahet: The Old Kingdom", short="OK", expansion="Wrath", kind="Dungeon", aliases={ "ok", "old kingdom", "ahn kahet", "ahnkahet" } },
        { id="dtk", name="Drak'Tharon Keep", short="DTK", expansion="Wrath", kind="Dungeon", aliases={ "dtk", "drak tharon", "drak'tharon keep" } },
        { id="vh", name="The Violet Hold", short="VH", expansion="Wrath", kind="Dungeon", aliases={ "vh", "violet hold" } },
        { id="gundrak", name="Gundrak", short="Gundrak", expansion="Wrath", kind="Dungeon", aliases={ "gundrak", "gund" } },
        { id="hos", name="Halls of Stone", short="HoS", expansion="Wrath", kind="Dungeon", aliases={ "hos", "halls of stone" } },
        { id="hol", name="Halls of Lightning", short="HoL", expansion="Wrath", kind="Dungeon", aliases={ "hol", "halls of lightning" } },
        { id="oculus", name="The Oculus", short="Oculus", expansion="Wrath", kind="Dungeon", aliases={ "oculus", "the oculus" } },
        { id="cos", name="The Culling of Stratholme", short="CoS", expansion="Wrath", kind="Dungeon", aliases={ "cos", "culling of stratholme", "culling", "cot4" } },
        { id="up", name="Utgarde Pinnacle", short="UP", expansion="Wrath", kind="Dungeon", aliases={ "up", "utgarde pinnacle" } },
        { id="toc5", name="Trial of the Champion", short="ToC5", expansion="Wrath", kind="Dungeon", aliases={ "toc5", "toc 5", "trial of the champion", "champion's trial", "champions trial" } },
        { id="fos", name="The Forge of Souls", short="FoS", expansion="Wrath", kind="Dungeon", aliases={ "fos", "forge of souls" } },
        { id="pos", name="Pit of Saron", short="PoS", expansion="Wrath", kind="Dungeon", aliases={ "pos", "pit of saron" } },
        { id="hor", name="Halls of Reflection", short="HoR", expansion="Wrath", kind="Dungeon", aliases={ "hor", "halls of reflection" } },
        { id="naxx", name="Naxxramas", short="Naxx", expansion="Wrath", kind="Raid", aliases={ "naxx", "naxxramas", "naxx10", "naxx 10", "naxx25", "naxx 25" } },
        { id="os", name="The Obsidian Sanctum", short="OS", expansion="Wrath", kind="Raid", aliases={ "os", "obsidian sanctum", "os10", "os 10", "os25", "os 25", "os3d", "os 3d" } },
        { id="eoe", name="The Eye of Eternity", short="EoE", expansion="Wrath", kind="Raid", aliases={ "eoe", "eye of eternity", "malygos raid" } },
        { id="voa", name="Vault of Archavon", short="VoA", expansion="Wrath", kind="Raid", aliases={ "voa", "vault of archavon", "voa10", "voa 10", "voa25", "voa 25" } },
        { id="ulduar", name="Ulduar", short="Ulduar", expansion="Wrath", kind="Raid", aliases={ "ulduar", "uld", "uld10", "uld 10", "uld25", "uld 25" } },
        { id="toc", name="Trial of the Crusader", short="ToC", expansion="Wrath", kind="Raid", aliases={ "toc", "toc10", "toc 10", "toc25", "toc 25", "trial of the crusader" } },
        { id="togc", name="Trial of the Grand Crusader", short="ToGC", expansion="Wrath", kind="Raid", aliases={ "togc", "togc10", "togc 10", "togc25", "togc 25", "grand crusader" } },
        { id="icc", name="Icecrown Citadel", short="ICC", expansion="Wrath", kind="Raid", aliases={ "icc", "icecrown citadel", "icc10", "icc 10", "icc25", "icc 25" } },
        { id="rs", name="The Ruby Sanctum", short="RS", expansion="Wrath", kind="Raid", aliases={ "rs", "ruby sanctum", "rs10", "rs 10", "rs25", "rs 25" } },
        { id="azuregos", name="Azuregos", short="Azuregos", expansion="Classic", kind="World Boss", aliases={ "azuregos" } },
        { id="kazzak", name="Lord Kazzak / Doom Lord Kazzak", short="Kazzak", expansion="TBC", kind="World Boss", aliases={ "lord kazzak", "doom lord kazzak", "kazzak" } },
        { id="doomwalker", name="Doomwalker", short="Doomwalker", expansion="TBC", kind="World Boss", aliases={ "doomwalker" } },
    },
    bosses = {
        { id="ragnaros", parent="mc", name="Ragnaros", short="Ragnaros", kind="Boss", standalone=true, aliases={ "ragnaros", "rag" } },
        { id="nefarian", parent="bwl", name="Nefarian", short="Nefarian", kind="Boss", standalone=true, aliases={ "nefarian", "nef" } },
        { id="hakkar", parent="zg", name="Hakkar", short="Hakkar", kind="Boss", standalone=true, aliases={ "hakkar" } },
        { id="cthun", parent="aq40", name="C'Thun", short="C'Thun", kind="Boss", standalone=true, aliases={ "cthun", "c thun" } },
        { id="twin_emps", parent="aq40", name="Twin Emperors", short="Twin Emps", kind="Boss", standalone=false, aliases={ "twin emperors", "twin emps", "twins" } },
        { id="attumen", parent="kara", name="Attumen the Huntsman", short="Attumen", kind="Boss", standalone=true, aliases={ "attumen" } },
        { id="moroes", parent="kara", name="Moroes", short="Moroes", kind="Boss", standalone=true, aliases={ "moroes" } },
        { id="maiden", parent="kara", name="Maiden of Virtue", short="Maiden", kind="Boss", standalone=false, aliases={ "maiden of virtue", "maiden" } },
        { id="opera", parent="kara", name="Opera Event", short="Opera", kind="Boss", standalone=false, aliases={ "opera", "opera event" } },
        { id="curator", parent="kara", name="The Curator", short="Curator", kind="Boss", standalone=true, aliases={ "curator" } },
        { id="illhoof", parent="kara", name="Terestian Illhoof", short="Illhoof", kind="Boss", standalone=true, aliases={ "illhoof", "terestian" } },
        { id="aran", parent="kara", name="Shade of Aran", short="Aran", kind="Boss", standalone=true, aliases={ "shade of aran", "aran" } },
        { id="netherspite", parent="kara", name="Netherspite", short="Netherspite", kind="Boss", standalone=true, aliases={ "netherspite" } },
        { id="malchezaar", parent="kara", name="Prince Malchezaar", short="Prince", kind="Boss", standalone=false, aliases={ "malchezaar", "prince malchezaar", "prince" } },
        { id="nightbane", parent="kara", name="Nightbane", short="Nightbane", kind="Boss", standalone=true, aliases={ "nightbane" } },
        { id="maulgar", parent="gruul", name="High King Maulgar", short="Maulgar", kind="Boss", standalone=true, aliases={ "maulgar" } },
        { id="gruul_boss", parent="gruul", name="Gruul the Dragonkiller", short="Gruul", kind="Boss", standalone=false, aliases={ "gruul" } },
        { id="magtheridon_boss", parent="mag", name="Magtheridon", short="Magtheridon", kind="Boss", standalone=false, aliases={ "magtheridon" } },
        { id="hydross", parent="ssc", name="Hydross the Unstable", short="Hydross", kind="Boss", standalone=true, aliases={ "hydross" } },
        { id="lurker", parent="ssc", name="The Lurker Below", short="Lurker", kind="Boss", standalone=true, aliases={ "lurker below", "lurker" } },
        { id="leotheras", parent="ssc", name="Leotheras the Blind", short="Leotheras", kind="Boss", standalone=true, aliases={ "leotheras", "leo" } },
        { id="morogrim", parent="ssc", name="Morogrim Tidewalker", short="Morogrim", kind="Boss", standalone=true, aliases={ "morogrim", "tidewalker" } },
        { id="vashj", parent="ssc", name="Lady Vashj", short="Vashj", kind="Boss", standalone=true, aliases={ "lady vashj", "vashj" } },
        { id="alar", parent="tk", name="Al'ar", short="Al'ar", kind="Boss", standalone=true, aliases={ "alar", "al ar" } },
        { id="void_reaver", parent="tk", name="Void Reaver", short="Void Reaver", kind="Boss", standalone=false, aliases={ "void reaver", "vr" } },
        { id="solarian", parent="tk", name="High Astromancer Solarian", short="Solarian", kind="Boss", standalone=true, aliases={ "solarian" } },
        { id="kael", parent="tk", name="Kael'thas Sunstrider", short="Kael'thas", kind="Boss", standalone=false, aliases={ "kaelthas", "kael thas", "kael" } },
        { id="archimonde", parent="hyjal", name="Archimonde", short="Archimonde", kind="Boss", standalone=true, aliases={ "archimonde" } },
        { id="teron", parent="bt", name="Teron Gorefiend", short="Teron", kind="Boss", standalone=true, aliases={ "teron gorefiend", "teron" } },
        { id="gurtogg", parent="bt", name="Gurtogg Bloodboil", short="Gurtogg", kind="Boss", standalone=true, aliases={ "gurtogg", "bloodboil" } },
        { id="reliquary", parent="bt", name="Reliquary of Souls", short="Reliquary", kind="Boss", standalone=true, aliases={ "reliquary", "reliquary of souls" } },
        { id="shahraz", parent="bt", name="Mother Shahraz", short="Shahraz", kind="Boss", standalone=true, aliases={ "shahraz", "mother shahraz" } },
        { id="illidan", parent="bt", name="Illidan Stormrage", short="Illidan", kind="Boss", standalone=true, aliases={ "illidan" } },
        { id="zuljin", parent="za", name="Zul'jin", short="Zul'jin", kind="Boss", standalone=true, aliases={ "zuljin", "zul jin" } },
        { id="brutallus", parent="swp", name="Brutallus", short="Brutallus", kind="Boss", standalone=true, aliases={ "brutallus" } },
        { id="felmyst", parent="swp", name="Felmyst", short="Felmyst", kind="Boss", standalone=true, aliases={ "felmyst" } },
        { id="muru", parent="swp", name="M'uru", short="M'uru", kind="Boss", standalone=true, aliases={ "muru", "m uru" } },
        { id="kiljaeden", parent="swp", name="Kil'jaeden", short="Kil'jaeden", kind="Boss", standalone=true, aliases={ "kiljaeden", "kil jaeden", "kj" } },
        { id="anubrekhan", parent="naxx", name="Anub'Rekhan", short="Anub'Rekhan", kind="Boss", standalone=true, aliases={ "anubrekhan", "anub rekhan" } },
        { id="faerlina", parent="naxx", name="Grand Widow Faerlina", short="Faerlina", kind="Boss", standalone=true, aliases={ "faerlina" } },
        { id="maexxna", parent="naxx", name="Maexxna", short="Maexxna", kind="Boss", standalone=true, aliases={ "maexxna" } },
        { id="heigan", parent="naxx", name="Heigan the Unclean", short="Heigan", kind="Boss", standalone=true, aliases={ "heigan" } },
        { id="loatheb", parent="naxx", name="Loatheb", short="Loatheb", kind="Boss", standalone=true, aliases={ "loatheb" } },
        { id="razuvious", parent="naxx", name="Instructor Razuvious", short="Razuvious", kind="Boss", standalone=true, aliases={ "razuvious" } },
        { id="gothik", parent="naxx", name="Gothik the Harvester", short="Gothik", kind="Boss", standalone=true, aliases={ "gothik" } },
        { id="horsemen", parent="naxx", name="The Four Horsemen", short="Four Horsemen", kind="Boss", standalone=false, aliases={ "four horsemen", "horsemen" } },
        { id="patchwerk", parent="naxx", name="Patchwerk", short="Patchwerk", kind="Boss", standalone=true, aliases={ "patchwerk" } },
        { id="grobbulus", parent="naxx", name="Grobbulus", short="Grobbulus", kind="Boss", standalone=true, aliases={ "grobbulus", "grob" } },
        { id="gluth", parent="naxx", name="Gluth", short="Gluth", kind="Boss", standalone=true, aliases={ "gluth" } },
        { id="thaddius", parent="naxx", name="Thaddius", short="Thaddius", kind="Boss", standalone=true, aliases={ "thaddius" } },
        { id="sapphiron", parent="naxx", name="Sapphiron", short="Sapphiron", kind="Boss", standalone=true, aliases={ "sapphiron", "sapph" } },
        { id="kelthuzad", parent="naxx", name="Kel'Thuzad", short="Kel'Thuzad", kind="Boss", standalone=false, aliases={ "kelthuzad", "kel thuzad", "kt" } },
        { id="sartharion", parent="os", name="Sartharion", short="Sartharion", kind="Boss", standalone=true, aliases={ "sartharion", "sarth" } },
        { id="malygos", parent="eoe", name="Malygos", short="Malygos", kind="Boss", standalone=true, aliases={ "malygos" } },
        { id="archavon", parent="voa", name="Archavon the Stone Watcher", short="Archavon", kind="Boss", standalone=true, aliases={ "archavon" } },
        { id="emalon", parent="voa", name="Emalon the Storm Watcher", short="Emalon", kind="Boss", standalone=true, aliases={ "emalon" } },
        { id="koralon", parent="voa", name="Koralon the Flame Watcher", short="Koralon", kind="Boss", standalone=true, aliases={ "koralon" } },
        { id="toravon", parent="voa", name="Toravon the Ice Watcher", short="Toravon", kind="Boss", standalone=true, aliases={ "toravon" } },
        { id="flame_leviathan", parent="ulduar", name="Flame Leviathan", short="Leviathan", kind="Boss", standalone=false, aliases={ "flame leviathan", "leviathan", "fl" } },
        { id="razorscale", parent="ulduar", name="Razorscale", short="Razorscale", kind="Boss", standalone=true, aliases={ "razorscale" } },
        { id="ignis", parent="ulduar", name="Ignis the Furnace Master", short="Ignis", kind="Boss", standalone=true, aliases={ "ignis" } },
        { id="xt", parent="ulduar", name="XT-002 Deconstructor", short="XT-002", kind="Boss", standalone=false, aliases={ "xt002", "xt 002", "xt" } },
        { id="iron_council", parent="ulduar", name="The Assembly of Iron", short="Iron Council", kind="Boss", standalone=false, aliases={ "iron council", "assembly of iron", "council" } },
        { id="kologarn", parent="ulduar", name="Kologarn", short="Kologarn", kind="Boss", standalone=true, aliases={ "kologarn" } },
        { id="auriaya", parent="ulduar", name="Auriaya", short="Auriaya", kind="Boss", standalone=true, aliases={ "auriaya" } },
        { id="hodir", parent="ulduar", name="Hodir", short="Hodir", kind="Boss", standalone=true, aliases={ "hodir" } },
        { id="thorim", parent="ulduar", name="Thorim", short="Thorim", kind="Boss", standalone=true, aliases={ "thorim" } },
        { id="freya", parent="ulduar", name="Freya", short="Freya", kind="Boss", standalone=true, aliases={ "freya" } },
        { id="mimiron", parent="ulduar", name="Mimiron", short="Mimiron", kind="Boss", standalone=true, aliases={ "mimiron", "firefighter" } },
        { id="vezax", parent="ulduar", name="General Vezax", short="Vezax", kind="Boss", standalone=true, aliases={ "vezax", "general vezax" } },
        { id="yogg", parent="ulduar", name="Yogg-Saron", short="Yogg", kind="Boss", standalone=true, aliases={ "yogg", "yogg saron", "yoggsaron" } },
        { id="algalon", parent="ulduar", name="Algalon the Observer", short="Algalon", kind="Boss", standalone=true, aliases={ "algalon" } },
        { id="beasts", parent="toc", name="Northrend Beasts", short="Beasts", kind="Boss", standalone=false, aliases={ "northrend beasts", "beasts" } },
        { id="jaraxxus", parent="toc", name="Lord Jaraxxus", short="Jaraxxus", kind="Boss", standalone=true, aliases={ "jaraxxus" } },
        { id="faction_champs", parent="toc", name="Faction Champions", short="Faction Champs", kind="Boss", standalone=false, aliases={ "faction champions", "faction champs" } },
        { id="valkyr_twins", parent="toc", name="Twin Val'kyr", short="Twin Val'kyr", kind="Boss", standalone=false, aliases={ "twin valkyr", "twin val kyr", "twins" } },
        { id="anubarak", parent="toc", name="Anub'arak", short="Anub'arak", kind="Boss", standalone=true, aliases={ "anubarak", "anub arak" } },
        { id="marrowgar", parent="icc", name="Lord Marrowgar", short="Marrowgar", kind="Boss", standalone=true, aliases={ "marrowgar" } },
        { id="deathwhisper", parent="icc", name="Lady Deathwhisper", short="Deathwhisper", kind="Boss", standalone=true, aliases={ "deathwhisper", "lady deathwhisper" } },
        { id="gunship", parent="icc", name="Gunship Battle", short="Gunship", kind="Boss", standalone=true, aliases={ "gunship", "gunship battle" } },
        { id="saurfang", parent="icc", name="Deathbringer Saurfang", short="Saurfang", kind="Boss", standalone=false, aliases={ "deathbringer saurfang", "saurfang", "dbs" } },
        { id="festergut", parent="icc", name="Festergut", short="Festergut", kind="Boss", standalone=true, aliases={ "festergut", "fester" } },
        { id="rotface", parent="icc", name="Rotface", short="Rotface", kind="Boss", standalone=true, aliases={ "rotface" } },
        { id="putricide", parent="icc", name="Professor Putricide", short="Putricide", kind="Boss", standalone=false, aliases={ "putricide", "professor putricide", "pp" } },
        { id="blood_princes", parent="icc", name="Blood Prince Council", short="Blood Princes", kind="Boss", standalone=true, aliases={ "blood prince council", "blood princes", "bpc" } },
        { id="lanathel", parent="icc", name="Blood-Queen Lana'thel", short="Lana'thel", kind="Boss", standalone=true, aliases={ "lanathel", "lana thel", "blood queen", "bql" } },
        { id="valithria", parent="icc", name="Valithria Dreamwalker", short="Valithria", kind="Boss", standalone=true, aliases={ "valithria", "dreamwalker" } },
        { id="sindragosa", parent="icc", name="Sindragosa", short="Sindragosa", kind="Boss", standalone=true, aliases={ "sindragosa", "sindra" } },
        { id="lich_king", parent="icc", name="The Lich King", short="Lich King", kind="Boss", standalone=false, aliases={ "lich king", "the lich king", "lk" } },
        { id="halion", parent="rs", name="Halion", short="Halion", kind="Boss", standalone=true, aliases={ "halion" } },
        { id="anzu", parent="sethekk", name="Anzu", short="Anzu", kind="Boss", standalone=true, aliases={ "anzu" } },
        { id="kael_mgt", parent="mgt", name="Kael'thas Sunstrider", short="Kael'thas", kind="Boss", standalone=false, aliases={ "kaelthas", "kael thas", "kael" } },
        { id="loken", parent="hol", name="Loken", short="Loken", kind="Boss", standalone=true, aliases={ "loken" } },
        { id="eregos", parent="oculus", name="Ley-Guardian Eregos", short="Eregos", kind="Boss", standalone=true, aliases={ "eregos" } },
        { id="ymiron", parent="up", name="King Ymiron", short="Ymiron", kind="Boss", standalone=true, aliases={ "ymiron" } },
        { id="malganis", parent="cos", name="Mal'Ganis", short="Mal'Ganis", kind="Boss", standalone=true, aliases={ "malganis", "mal ganis" } },
        { id="black_knight", parent="toc5", name="The Black Knight", short="Black Knight", kind="Boss", standalone=true, aliases={ "black knight" } },
        { id="devourer", parent="fos", name="Devourer of Souls", short="Devourer", kind="Boss", standalone=true, aliases={ "devourer of souls", "devourer" } },
        { id="tyrannus", parent="pos", name="Scourgelord Tyrannus", short="Tyrannus", kind="Boss", standalone=true, aliases={ "tyrannus", "scourgelord" } },
        { id="falric", parent="hor", name="Falric", short="Falric", kind="Boss", standalone=true, aliases={ "falric" } },
        { id="marwyn", parent="hor", name="Marwyn", short="Marwyn", kind="Boss", standalone=true, aliases={ "marwyn" } },
    },
    suppress = {
        ["sm_gy"]={"sm"}, ["sm_lib"]={"sm"}, ["sm_arm"]={"sm"}, ["sm_cath"]={"sm"},
        ["dme"]={"diremaul"}, ["dmw"]={"diremaul"}, ["dmn"]={"diremaul"},
        ["toc5"]={"toc"}, ["togc"]={"toc"},
    },
}
